// Generated by ts-to-zod
import { z } from 'zod'
import type { Json } from './../types/supabase.d'

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
)

export const profilesRowSchema = z.object({
  id: z.string(),
  updated_at: z.string().nullable(),
  username: z.string().nullable(),
})

export const profilesInsertSchema = z.object({
  id: z.string(),
  updated_at: z.string().optional().nullable(),
  username: z.string().optional().nullable(),
})

export const profilesUpdateSchema = z.object({
  id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  username: z.string().optional().nullable(),
})

export const profilesRelationshipsSchema = z.tuple([])
